name: cached
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  built_collection: ^5.1.1
  collection: ^1.19.0
  objectbox: ^4.3.0
  objectbox_generator: ^4.3.0
  objectbox_sync_flutter_libs: ^4.3.0
  super_annotations: ^0.9.0

dev_dependencies:
  build_runner: ^2.5.0
  lints: ^5.0.0
  test: ^1.24.0
